name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install --force

      - name: Build
        run: npm run build

      # - name: Deploy to GitHub Pages
      #   run: |
      #     git clone https://github.com/${{ github.repository }} --branch=gh-pages --single-branch gh-pages
      #     cd gh-pages
      #     git rm -rf .
      #     cp -r ../build/* ./docs
      #     git add .
      #     git commit -m "Deploy to GitHub Pages"
      #     git push --force https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
      #   env:
      #     NODE_ENV: production
